### ISSUE TITLE
Python version mistake

### ISSUE THREAD

**Issue by hidoba** [BAILOOL/ANMS-Codes#12]
To make it work properly with rectangular images,

`covered_vec = [[False for _ in range(num_cell_cols + 1)] for _ in range(num_cell_cols + 1)]`

has to be

`covered_vec = [[False for _ in range(num_cell_cols + 1)] for _ in range(num_cell_rows + 1)]`

**Comment by BAILOOL** [comment]
Great catch @hidoba. Thank you very much!
