### ISSUE TITLE
Error C2334 unexpected token(s) preceding '{'; skipping apparent function body

### ISSUE THREAD

**Issue by CookingCookie** [BAILOOL/ANMS-Codes#2]
When compiling the CmakeProject on Windows 7 for Visual Studio 15 2017 Win64 with OpenCV 3 I get a lot of errors.

The first one is for example:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	C2334	unexpected token(s) preceding '{'; skipping apparent function body	ANMS_Codes	c:\users\cookie\documents\anms\cmakeproject\source\range-tree\ranget.h	523	
`

Is the code not compatible with my setup or have I simply missed something?

**Comment by BAILOOL** [comment]
@CookingCookie, unfortunately, I have zero experience with Windows 7 with VS and OpenCV, so it would be hard to help you on the issue. However, range tree library (where the error occurs) is only used in different algorithms for comparison purposes. The algorithm that we suggest in the paper is SSC, and it only relies on OpenCV (any version) with no additional libraries. So I would suggest you keeping [Ssc](https://github.com/BAILOOL/ANMS-Codes/blob/4a57d56ca546676789909f43de56b056ffbab7b9/CmakeProject/source/anms.h#L292) only while removing everything redundant (including ranget.h headers)

**Comment by CookingCookie** [comment]
Yes this worked. It compiled and is runnable.
Thanks for the quick response!
