### ISSUE TITLE
Getting std::bad_alloc error when using SSC function

### ISSUE THREAD

**Issue by JeffR1992** [BAILOOL/ANMS-Codes#35]
I'm getting an `std::bad_alloc` error when testing a visual odometry algorithm, that uses the `ssc()` function (suppression via square covering) (in this case it is occurring on the Kitti sequence 01 odometry dataset). The error occurs on the line that says:

`std::vector<std::vector<bool>> coveredVec(numCellRows + 1, std::vector<bool>(numCellCols + 1, false));`

The root-cause of the issue occurs a few lines up when `width = 1`, since the variable `c` is defined as:

`double c = width / 2;`

which will cause `c = 1/2 = 0` due to integer division. This then has the follow-on effect that `numCellCols` and `numCellRows` are undefined since they are created by dividing by `c` (which is `0` in this case).

I can fix the issue by simply defining `c` using floating point division instead of integer division (i.e. `double c = width / 2.0`). However, as I do not have enough time to delve deep into the theory, I wanted to ask if this "fix" is theoretically sound. Thanks.

**Comment by BAILOOL** [comment]
Hi @JeffR1992. Thank you very much for pointing it out. The observation is correct and the solution you proposed is theoretically sound. In fact, the exact same bug was reported in #4 and was actually fixed in #5. Though it was fixed in `CmakeProject` and I guess you use `QtProject`. I would recommend to use the proposed fix.

Meanwhile, I will aim at unifying those folders this weekend in order to avoid this situation again.

**Comment by JeffR1992** [comment]
Aha thanks @BAILOOL, for some reason I didn't see that issue posted. Another issue I noticed that also occurs is when `width=0`, in which case `ssc()` crashes again with an `std::bad_alloc` error. Has this also been fixed in the `CmakeProject` version, or is that still an open issue? Thanks!

**Comment by BAILOOL** [comment]
@JeffR1992  The `width=0` doesn't make any sense as it is smaller than a pixel. I don't recall seeing this bug before. Could you please point out the line where this error happen?

**Comment by JeffR1992** [comment]
This seems to take place in situations when `low=0` and `high=1`. The following values cause this to occur:

`keyPoints.size() = 435`
`numRetPoints = 500`
`tolerance = 0.1`
`cols = 848`
`rows = 480`

Looking at the values defined in the `ssc()` function I get:

`exp1 = 2328`
`exp2 = 815180816`
`exp3 = 28551.4`
`exp4 = 499`
`sol1 = -62`
`sol2 = 53`
`low = 0`
`high = 53`
