### ISSUE TITLE
std::bad_alloc in anms.h

### ISSUE THREAD

**Issue by drondao** [BAILOOL/ANMS-Codes#4]
In "anms.h", the following line assigns `c = 0` when `width = 1` because of integer division:

`double c = width/2; //initializing Grid`

This causes the assignment of infinity to

`int numCellCols = floor(cols/c);`
` int numCellRows = floor(rows/c);`

which, in turn, returns an `std::bad_alloc` exception because of the call

`std::vector<std::vector<bool> > coveredVec(numCellRows+1,std::vector<bool>(numCellCols+1,false));`

**Comment by BAILOOL** [comment]
@drondao Thank you for pointing it out. Feel free to commit changes through the pull request.
